/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.tp6;

import javax.swing.JOptionPane;

/**
 *
 * @author br1st
 */
public class GestionDeProductosView extends javax.swing.JInternalFrame {

    /**
     * Creates new form BusquedaPorRubroView
     */
    public GestionDeProductosView() {
        initComponents();
        cargarCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtDescripcion = new javax.swing.JTextField();
        jtCodigo = new javax.swing.JTextField();
        jtPrecio = new javax.swing.JTextField();
        jtStock = new javax.swing.JTextField();
        jcRubro = new javax.swing.JComboBox<>();
        jbBuscar = new javax.swing.JButton();
        jbNuevo = new javax.swing.JButton();
        jbGuardar = new javax.swing.JButton();
        jbEliminar = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Gestión de Productos");

        jLabel2.setText("Código");

        jLabel3.setText("Descripción");

        jLabel4.setText("Precio");

        jLabel5.setText("Rubro");

        jLabel6.setText("Stock");

        jbBuscar.setIcon(new javax.swing.ImageIcon("C:\\Users\\br1st\\Downloads\\lupa2.png")); // NOI18N
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jbNuevo.setText("Nuevo");
        jbNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevoActionPerformed(evt);
            }
        });

        jbGuardar.setText("Guardar");
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });

        jbEliminar.setText("Eliminar");
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });

        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(101, 101, 101))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbBuscar))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jbGuardar)
                                        .addComponent(jcRubro, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jbEliminar))
                                .addComponent(jtDescripcion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jtStock, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jbNuevo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(jbSalir)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbBuscar)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jcRubro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbNuevo)
                    .addComponent(jbGuardar)
                    .addComponent(jbEliminar)
                    .addComponent(jbSalir))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jbNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevoActionPerformed
        // TODO add your handling code here:
        jtCodigo.setText("");
        jtDescripcion.setText("");
        jtPrecio.setText("");
        jcRubro.setSelectedIndex(-1);
        jtStock.setText("");
        
    }//GEN-LAST:event_jbNuevoActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        // TODO add your handling code here:
        try{
            int codigo = Integer.parseInt(jtCodigo.getText());
        
            for(Producto prod: MenuView.listaProductos) {
            
                if( prod.getCodigo() == codigo) {
                    Producto prodEncontrado = prod;
                    jtDescripcion.setText(prodEncontrado.getDescripcion());
                    jtPrecio.setText(prodEncontrado.getPrecio() + "");
                    jcRubro.setSelectedItem(prodEncontrado.getRubro());
                    jtStock.setText(prodEncontrado.getStock() + "");
                    return;
                }
            }
        
            // si recorrió toda la lista y ninguna coincidía, no existe un prod con ese codigo.
            JOptionPane.showMessageDialog(this, "No existe un producto con ese id");
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "El codigo debe ser un entero");
        }
        
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed
        // TODO add your handling code here:
        try{
            int codigo = Integer.parseInt(jtCodigo.getText());
            String descripcion = jtDescripcion.getText();
            double precio = Double.parseDouble(jtPrecio.getText());
            Categoria rubro = (Categoria) jcRubro.getSelectedItem();
            int stock = Integer.parseInt(jtStock.getText());
            
            // Antes de crear el nuevo producto, verifico que no exista uno con el mismo codigo
//            for(Producto prod: MenuView.listaProductos){
//                if(prod.getCodigo() == codigo){
//                    JOptionPane.showMessageDialog(this, "Ya existe un producto con ese codigo");
//                    return;
//                }
//            }
            
            if(descripcion.length() == 0 || jcRubro.getSelectedIndex() == -1){
                JOptionPane.showMessageDialog(this, "No puede haber campos vacíos");
                return;
            }
            
            // Metodo alternativo para fijarme si hay un producto igual antes y guardarlo en los comentarios del mismo metodo:
            boolean repetido = MenuView.listaProductos.add(new Producto(codigo, descripcion, precio, stock, rubro));
            if(repetido){
                JOptionPane.showMessageDialog(this, "Producto guardado con exito");
            }else{
                JOptionPane.showMessageDialog(this, "Ya existe un producto con ese codigo");
            }
            
            
            // Creo el producto y lo agrego
//            Producto prodNuevo = new Producto(codigo, descripcion, precio, stock, rubro);
//            MenuView.listaProductos.add(prodNuevo);
//            JOptionPane.showMessageDialog(this, "Producto guardado con exito");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "error de formato, el codigo debe ser un numero entero, el precio un real, y el stock un entero");
        }
    }//GEN-LAST:event_jbGuardarActionPerformed

    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed
        // TODO add your handling code here:
        try{

            int codigo = Integer.parseInt(jtCodigo.getText());
            
            //me fijo si existe un producto con ese codigo?
            for(Producto prod:MenuView.listaProductos){
                
                if(prod.getCodigo() == codigo){
                    
                    // Si existe lo muestro por pantalla
                    jtDescripcion.setText(prod.getDescripcion());
                    jtPrecio.setText(prod.getPrecio() + "");
                    jcRubro.setSelectedItem(prod.getRubro());
                    jtStock.setText(prod.getStock() + "");
                    
                    // Y confirmo que sea el que se desea eliminar
                    if(JOptionPane.showConfirmDialog(this, "Esta seguro que desea eliminar el siguiente producto") == 0){
                        
                        // Lo elimino
                        MenuView.listaProductos.remove(prod);
                        JOptionPane.showMessageDialog(this, "Producto con codigo: " + codigo + " eliminado");
                        
                        // Luego de eliminar, limpio la pantalla
                        jbNuevoActionPerformed(evt);
                        return;
                    }
                    
                    // Si le da a "no" o a "cancel", cancelo y limpio la pantalla, y salgo del bucle
                    JOptionPane.showMessageDialog(this, "Accion cancelada");
                    jbNuevoActionPerformed(evt);
                    return;
                }                               
            }
            
            JOptionPane.showMessageDialog(this, "No existe un producto con ese codigo");           
            
        }catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El codigo debe ser un entero");
        }
    }//GEN-LAST:event_jbEliminarActionPerformed

    private void cargarCombo() {
        jcRubro.addItem(Categoria.LIMPIEZA);
        jcRubro.addItem(Categoria.COMESTIBLE);
        jcRubro.addItem(Categoria.PERFUMERIA);
        jcRubro.setSelectedIndex(-1);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JButton jbNuevo;
    private javax.swing.JButton jbSalir;
    private javax.swing.JComboBox<Categoria> jcRubro;
    private javax.swing.JTextField jtCodigo;
    private javax.swing.JTextField jtDescripcion;
    private javax.swing.JTextField jtPrecio;
    private javax.swing.JTextField jtStock;
    // End of variables declaration//GEN-END:variables
}
