/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tp6;

import java.util.TreeSet;

/**
 *
 * @author br1st
 */
public class MenuView extends javax.swing.JFrame {
    
    public static TreeSet<Producto> listaProductos = new TreeSet<>();

    /**
     * Creates new form MenuView
     */
    public MenuView() {
        initComponents();
        cargarProductos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmAdministracion = new javax.swing.JMenu();
        jmiAdmProductos = new javax.swing.JMenuItem();
        jmConsultas = new javax.swing.JMenu();
        jmiConsultaPorRubro = new javax.swing.JMenuItem();
        jmiConsultaPorNombre = new javax.swing.JMenuItem();
        jmiConsultaPorPrecio = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 600));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        jmAdministracion.setText("Administracion");

        jmiAdmProductos.setText("Productos");
        jmiAdmProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAdmProductosActionPerformed(evt);
            }
        });
        jmAdministracion.add(jmiAdmProductos);

        jMenuBar1.add(jmAdministracion);

        jmConsultas.setText("Consultas");

        jmiConsultaPorRubro.setText("Por rubro...");
        jmiConsultaPorRubro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiConsultaPorRubroActionPerformed(evt);
            }
        });
        jmConsultas.add(jmiConsultaPorRubro);

        jmiConsultaPorNombre.setText("Por nombre...");
        jmiConsultaPorNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiConsultaPorNombreActionPerformed(evt);
            }
        });
        jmConsultas.add(jmiConsultaPorNombre);

        jmiConsultaPorPrecio.setText("Por precio...");
        jmiConsultaPorPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiConsultaPorPrecioActionPerformed(evt);
            }
        });
        jmConsultas.add(jmiConsultaPorPrecio);

        jMenuBar1.add(jmConsultas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiConsultaPorNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiConsultaPorNombreActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        BusquedaPorNombreView bpn = new BusquedaPorNombreView();
        bpn.setVisible(true);
        escritorio.add(bpn);
        escritorio.moveToFront(bpn);
    }//GEN-LAST:event_jmiConsultaPorNombreActionPerformed

    private void jmiAdmProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAdmProductosActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        GestionDeProductosView gdpv = new GestionDeProductosView();
        gdpv.setVisible(true);
        escritorio.add(gdpv);
        escritorio.moveToFront(gdpv);
    }//GEN-LAST:event_jmiAdmProductosActionPerformed

    private void jmiConsultaPorRubroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiConsultaPorRubroActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        BusquedaPorRubroView bprv = new BusquedaPorRubroView();
        bprv.setVisible(true);
        escritorio.add(bprv);
        escritorio.moveToFront(bprv);
    }//GEN-LAST:event_jmiConsultaPorRubroActionPerformed

    private void jmiConsultaPorPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiConsultaPorPrecioActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        BusquedaPorPrecioView bppv = new BusquedaPorPrecioView();
        bppv.setVisible(true);
        escritorio.add(bppv);
        escritorio.moveToFront(bppv);
    }//GEN-LAST:event_jmiConsultaPorPrecioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuView().setVisible(true);
            }
        });
    }

    private void cargarProductos() {
        listaProductos.add(new Producto(10, "Azucar x 1 Kg", 180.75, 5, Categoria.COMESTIBLE));
        listaProductos.add(new Producto(12, "Yerba Mate", 850, 10, Categoria.COMESTIBLE));
        listaProductos.add(new Producto(5, "Aceite de Girasol", 250.5, 5, Categoria.COMESTIBLE));
        listaProductos.add(new Producto(20, "Detergente x 1 Litro", 120.0, 15, Categoria.LIMPIEZA));
        listaProductos.add(new Producto(8, "Jabón en Barra", 30.25, 30, Categoria.LIMPIEZA));
        listaProductos.add(new Producto(15, "Champú Anticaspa", 220.0, 8, Categoria.PERFUMERIA));
        listaProductos.add(new Producto(25, "Perfume Floral", 450.0, 3, Categoria.PERFUMERIA));
        listaProductos.add(new Producto(3, "Arroz x 5 Kg", 350.0, 12, Categoria.COMESTIBLE));
        listaProductos.add(new Producto(7, "Leche Descremada x 1 Litro", 60.5, 20, Categoria.COMESTIBLE));
        listaProductos.add(new Producto(30, "Pan Blanco", 25.0, 50, Categoria.COMESTIBLE));
        listaProductos.add(new Producto(35, "Papel Higiénico x 4 Rollos", 80.0, 25, Categoria.LIMPIEZA));
        listaProductos.add(new Producto(40, "Shampoo de Volumen", 180.0, 15, Categoria.PERFUMERIA));
        listaProductos.add(new Producto(45, "Sal Refinada x 500g", 12.0, 40, Categoria.COMESTIBLE));
        listaProductos.add(new Producto(50, "Chocolate Negro", 45.0, 20, Categoria.COMESTIBLE));
        listaProductos.add(new Producto(55, "Lavavajillas Líquido", 70.0, 10, Categoria.LIMPIEZA));
        listaProductos.add(new Producto(60, "Colonia Floral", 120.0, 18, Categoria.PERFUMERIA));
        listaProductos.add(new Producto(65, "Pasta de Dientes", 40.0, 30, Categoria.PERFUMERIA));


    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jmAdministracion;
    private javax.swing.JMenu jmConsultas;
    private javax.swing.JMenuItem jmiAdmProductos;
    private javax.swing.JMenuItem jmiConsultaPorNombre;
    private javax.swing.JMenuItem jmiConsultaPorPrecio;
    private javax.swing.JMenuItem jmiConsultaPorRubro;
    // End of variables declaration//GEN-END:variables
}
